[package]
name = "sodium_sys"
version = "0.1.0"
edition = "2021"
links = "sodium"
build = "build.rs"

[dependencies]

[dev-dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.59.2"